[versions]
minecraft = "1.20.6"
fabricLoader = "0.15.10"
fabricApi = "0.97.8+1.20.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
